//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace UclOpenAuditoryVrCorridorDataSchema
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Represents a Harp Behavior Board device.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents a Harp Behavior Board device.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class BehaviorBoard
    {
    
        private string _deviceType;
    
        private string _portName;
    
        private PulseController _pulseController;
    
        private CameraController _cameraController;
    
        private RunningWheelModule _runningWheel;
    
        public BehaviorBoard()
        {
            _deviceType = "BehaviorBoard";
        }
    
        protected BehaviorBoard(BehaviorBoard other)
        {
            _deviceType = other._deviceType;
            _portName = other._portName;
            _pulseController = other._pulseController;
            _cameraController = other._cameraController;
            _runningWheel = other._runningWheel;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("deviceType")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Optional PulseController module for generating digital output pulses.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("pulseController")]
        [System.ComponentModel.DescriptionAttribute("Optional PulseController module for generating digital output pulses.")]
        public PulseController PulseController
        {
            get
            {
                return _pulseController;
            }
            set
            {
                _pulseController = value;
            }
        }
    
        /// <summary>
        /// Optional CameraController module for emitting camera trigger pulses.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("cameraController")]
        [System.ComponentModel.DescriptionAttribute("Optional CameraController module for emitting camera trigger pulses.")]
        public CameraController CameraController
        {
            get
            {
                return _cameraController;
            }
            set
            {
                _cameraController = value;
            }
        }
    
        /// <summary>
        /// Optional RunningWheelModule module to define wheel geometry.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("runningWheel")]
        [System.ComponentModel.DescriptionAttribute("Optional RunningWheelModule module to define wheel geometry.")]
        public RunningWheelModule RunningWheel
        {
            get
            {
                return _runningWheel;
            }
            set
            {
                _runningWheel = value;
            }
        }
    
        public System.IObservable<BehaviorBoard> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new BehaviorBoard(this)));
        }
    
        public System.IObservable<BehaviorBoard> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new BehaviorBoard(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("PulseController = " + _pulseController + ", ");
            stringBuilder.Append("CameraController = " + _cameraController + ", ");
            stringBuilder.Append("RunningWheel = " + _runningWheel);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents a CameraController Module for a BehaviourBoard device.
    ///Mirrors the externalized properties of the Bonsai workflow of the same name,
    ///excluding subject name properties.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents a CameraController Module for a BehaviourBoard device.\nMirrors the ext" +
        "ernalized properties of the Bonsai workflow of the same name,\nexcluding subject " +
        "name properties.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraController
    {
    
        private int _triggerFrequency;
    
        public CameraController()
        {
        }
    
        protected CameraController(CameraController other)
        {
            _triggerFrequency = other._triggerFrequency;
        }
    
        /// <summary>
        /// The frequency, in Hz, at which to emit camera triggers from DO0 of a behavior board (`CameraOutput0`)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("triggerFrequency", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The frequency, in Hz, at which to emit camera triggers from DO0 of a behavior boa" +
            "rd (`CameraOutput0`)")]
        public int TriggerFrequency
        {
            get
            {
                return _triggerFrequency;
            }
            set
            {
                _triggerFrequency = value;
            }
        }
    
        public System.IObservable<CameraController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraController(this)));
        }
    
        public System.IObservable<CameraController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("TriggerFrequency = " + _triggerFrequency);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents the PulseController module on the BehaviourBoard.
    ///Mirrors the externalized properties of the Bonsai workflow of the same name,
    ///excluding subject name properties.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents the PulseController module on the BehaviourBoard.\nMirrors the external" +
        "ized properties of the Bonsai workflow of the same name,\nexcluding subject name " +
        "properties.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PulseController
    {
    
        private System.Collections.Generic.List<string> _outputPulseEnable;
    
        private PulseWidths _pulseWidths;
    
        public PulseController()
        {
            _outputPulseEnable = new System.Collections.Generic.List<string>();
            _pulseWidths = new PulseWidths();
        }
    
        protected PulseController(PulseController other)
        {
            _outputPulseEnable = other._outputPulseEnable;
            _pulseWidths = other._pulseWidths;
        }
    
        /// <summary>
        /// List of digital output lines that are enabled for pulse generation.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("outputPulseEnable")]
        [System.ComponentModel.DescriptionAttribute("List of digital output lines that are enabled for pulse generation.")]
        public System.Collections.Generic.List<string> OutputPulseEnable
        {
            get
            {
                return _outputPulseEnable;
            }
            set
            {
                _outputPulseEnable = value;
            }
        }
    
        /// <summary>
        /// Pulse width configuration for DO1, DO2, and DO3 lines.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("pulseWidths", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Pulse width configuration for DO1, DO2, and DO3 lines.")]
        public PulseWidths PulseWidths
        {
            get
            {
                return _pulseWidths;
            }
            set
            {
                _pulseWidths = value;
            }
        }
    
        public System.IObservable<PulseController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PulseController(this)));
        }
    
        public System.IObservable<PulseController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PulseController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OutputPulseEnable = " + _outputPulseEnable + ", ");
            stringBuilder.Append("PulseWidths = " + _pulseWidths);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PulseWidths
    {
    
        private int _pulseDO1;
    
        private int _pulseDO2;
    
        private int _pulseDO3;
    
        public PulseWidths()
        {
        }
    
        protected PulseWidths(PulseWidths other)
        {
            _pulseDO1 = other._pulseDO1;
            _pulseDO2 = other._pulseDO2;
            _pulseDO3 = other._pulseDO3;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("PulseDO1", Required=Newtonsoft.Json.Required.Always)]
        public int PulseDO1
        {
            get
            {
                return _pulseDO1;
            }
            set
            {
                _pulseDO1 = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("PulseDO2", Required=Newtonsoft.Json.Required.Always)]
        public int PulseDO2
        {
            get
            {
                return _pulseDO2;
            }
            set
            {
                _pulseDO2 = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("PulseDO3", Required=Newtonsoft.Json.Required.Always)]
        public int PulseDO3
        {
            get
            {
                return _pulseDO3;
            }
            set
            {
                _pulseDO3 = value;
            }
        }
    
        public System.IObservable<PulseWidths> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PulseWidths(this)));
        }
    
        public System.IObservable<PulseWidths> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PulseWidths(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PulseDO1 = " + _pulseDO1 + ", ");
            stringBuilder.Append("PulseDO2 = " + _pulseDO2 + ", ");
            stringBuilder.Append("PulseDO3 = " + _pulseDO3);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Punishment-related parameters.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Punishment-related parameters.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PunishmentConfig
    {
    
        private int _timeoutSec;
    
        private int _stage4PunishedLick;
    
        private int _stage5PunishedLick;
    
        private int _stage6PunishedLick;
    
        public PunishmentConfig()
        {
            _timeoutSec = 5;
            _stage4PunishedLick = 5;
            _stage5PunishedLick = 4;
            _stage6PunishedLick = 3;
        }
    
        protected PunishmentConfig(PunishmentConfig other)
        {
            _timeoutSec = other._timeoutSec;
            _stage4PunishedLick = other._stage4PunishedLick;
            _stage5PunishedLick = other._stage5PunishedLick;
            _stage6PunishedLick = other._stage6PunishedLick;
        }
    
        /// <summary>
        /// Timeout duration in seconds
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("timeoutSec")]
        [System.ComponentModel.DescriptionAttribute("Timeout duration in seconds")]
        public int TimeoutSec
        {
            get
            {
                return _timeoutSec;
            }
            set
            {
                _timeoutSec = value;
            }
        }
    
        /// <summary>
        /// Licks before punishment in stage 4
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("stage4PunishedLick")]
        [System.ComponentModel.DescriptionAttribute("Licks before punishment in stage 4")]
        public int Stage4PunishedLick
        {
            get
            {
                return _stage4PunishedLick;
            }
            set
            {
                _stage4PunishedLick = value;
            }
        }
    
        /// <summary>
        /// Licks before punishment in stage 5
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("stage5PunishedLick")]
        [System.ComponentModel.DescriptionAttribute("Licks before punishment in stage 5")]
        public int Stage5PunishedLick
        {
            get
            {
                return _stage5PunishedLick;
            }
            set
            {
                _stage5PunishedLick = value;
            }
        }
    
        /// <summary>
        /// Licks before punishment in stage 6
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("stage6PunishedLick")]
        [System.ComponentModel.DescriptionAttribute("Licks before punishment in stage 6")]
        public int Stage6PunishedLick
        {
            get
            {
                return _stage6PunishedLick;
            }
            set
            {
                _stage6PunishedLick = value;
            }
        }
    
        public System.IObservable<PunishmentConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PunishmentConfig(this)));
        }
    
        public System.IObservable<PunishmentConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PunishmentConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("TimeoutSec = " + _timeoutSec + ", ");
            stringBuilder.Append("Stage4PunishedLick = " + _stage4PunishedLick + ", ");
            stringBuilder.Append("Stage5PunishedLick = " + _stage5PunishedLick + ", ");
            stringBuilder.Append("Stage6PunishedLick = " + _stage6PunishedLick);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents the RunningWheel Bonsai workflow module.
    ///Exposes wheel geometry parameters used to compute speed and distance from encoder counts.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents the RunningWheel Bonsai workflow module.\nExposes wheel geometry parame" +
        "ters used to compute speed and distance from encoder counts.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class RunningWheelModule
    {
    
        private int _countsPerRev;
    
        private double _wheelDiameterMm;
    
        public RunningWheelModule()
        {
        }
    
        protected RunningWheelModule(RunningWheelModule other)
        {
            _countsPerRev = other._countsPerRev;
            _wheelDiameterMm = other._wheelDiameterMm;
        }
    
        /// <summary>
        /// Number of encoder counts per full revolution of the running wheel.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("countsPerRev", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Number of encoder counts per full revolution of the running wheel.")]
        public int CountsPerRev
        {
            get
            {
                return _countsPerRev;
            }
            set
            {
                _countsPerRev = value;
            }
        }
    
        /// <summary>
        /// The diameter, in millimeters, of the running wheel.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("wheelDiameterMm", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The diameter, in millimeters, of the running wheel.")]
        public double WheelDiameterMm
        {
            get
            {
                return _wheelDiameterMm;
            }
            set
            {
                _wheelDiameterMm = value;
            }
        }
    
        public System.IObservable<RunningWheelModule> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RunningWheelModule(this)));
        }
    
        public System.IObservable<RunningWheelModule> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RunningWheelModule(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CountsPerRev = " + _countsPerRev + ", ");
            stringBuilder.Append("WheelDiameterMm = " + _wheelDiameterMm);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Frequency boundaries for a single shaping stage.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Frequency boundaries for a single shaping stage.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Stage
    {
    
        private int _floor;
    
        private int _ceiling;
    
        public Stage()
        {
        }
    
        protected Stage(Stage other)
        {
            _floor = other._floor;
            _ceiling = other._ceiling;
        }
    
        /// <summary>
        /// Lower frequency threshold (Hz)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("floor", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Lower frequency threshold (Hz)")]
        public int Floor
        {
            get
            {
                return _floor;
            }
            set
            {
                _floor = value;
            }
        }
    
        /// <summary>
        /// Upper frequency ceiling (Hz)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("ceiling", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Upper frequency ceiling (Hz)")]
        public int Ceiling
        {
            get
            {
                return _ceiling;
            }
            set
            {
                _ceiling = value;
            }
        }
    
        public System.IObservable<Stage> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Stage(this)));
        }
    
        public System.IObservable<Stage> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Stage(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Floor = " + _floor + ", ");
            stringBuilder.Append("Ceiling = " + _ceiling);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Threshold and ceiling frequencies for each shaping stage.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Threshold and ceiling frequencies for each shaping stage.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ThresholdFrequencies
    {
    
        private Stage _stage1;
    
        private Stage _stage2;
    
        private Stage _stage3;
    
        private Stage _stage4;
    
        private Stage _stage5;
    
        private Stage _stage6;
    
        public ThresholdFrequencies()
        {
            _stage1 = new Stage();
            _stage2 = new Stage();
            _stage3 = new Stage();
            _stage4 = new Stage();
            _stage5 = new Stage();
            _stage6 = new Stage();
        }
    
        protected ThresholdFrequencies(ThresholdFrequencies other)
        {
            _stage1 = other._stage1;
            _stage2 = other._stage2;
            _stage3 = other._stage3;
            _stage4 = other._stage4;
            _stage5 = other._stage5;
            _stage6 = other._stage6;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("stage1")]
        public Stage Stage1
        {
            get
            {
                return _stage1;
            }
            set
            {
                _stage1 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("stage2")]
        public Stage Stage2
        {
            get
            {
                return _stage2;
            }
            set
            {
                _stage2 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("stage3")]
        public Stage Stage3
        {
            get
            {
                return _stage3;
            }
            set
            {
                _stage3 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("stage4")]
        public Stage Stage4
        {
            get
            {
                return _stage4;
            }
            set
            {
                _stage4 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("stage5")]
        public Stage Stage5
        {
            get
            {
                return _stage5;
            }
            set
            {
                _stage5 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("stage6")]
        public Stage Stage6
        {
            get
            {
                return _stage6;
            }
            set
            {
                _stage6 = value;
            }
        }
    
        public System.IObservable<ThresholdFrequencies> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ThresholdFrequencies(this)));
        }
    
        public System.IObservable<ThresholdFrequencies> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ThresholdFrequencies(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Stage1 = " + _stage1 + ", ");
            stringBuilder.Append("Stage2 = " + _stage2 + ", ");
            stringBuilder.Append("Stage3 = " + _stage3 + ", ");
            stringBuilder.Append("Stage4 = " + _stage4 + ", ");
            stringBuilder.Append("Stage5 = " + _stage5 + ", ");
            stringBuilder.Append("Stage6 = " + _stage6);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenAuditoryVrCorridorRig
    {
    
        private string _version;
    
        private BehaviorBoard _behaviorboard;
    
        private RunningWheelModule _runningwheel;
    
        public UclOpenAuditoryVrCorridorRig()
        {
            _version = "0.0.0-rc1";
            _behaviorboard = new BehaviorBoard();
            _runningwheel = new RunningWheelModule();
        }
    
        protected UclOpenAuditoryVrCorridorRig(UclOpenAuditoryVrCorridorRig other)
        {
            _version = other._version;
            _behaviorboard = other._behaviorboard;
            _runningwheel = other._runningwheel;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("behaviorboard", Required=Newtonsoft.Json.Required.Always)]
        public BehaviorBoard Behaviorboard
        {
            get
            {
                return _behaviorboard;
            }
            set
            {
                _behaviorboard = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("runningwheel", Required=Newtonsoft.Json.Required.Always)]
        public RunningWheelModule Runningwheel
        {
            get
            {
                return _runningwheel;
            }
            set
            {
                _runningwheel = value;
            }
        }
    
        public System.IObservable<UclOpenAuditoryVrCorridorRig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenAuditoryVrCorridorRig(this)));
        }
    
        public System.IObservable<UclOpenAuditoryVrCorridorRig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenAuditoryVrCorridorRig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Behaviorboard = " + _behaviorboard + ", ");
            stringBuilder.Append("Runningwheel = " + _runningwheel);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Top-level task logic schema.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Top-level task logic schema.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenAuditoryVrCorridorTaskLogic
    {
    
        private string _version;
    
        private string _name;
    
        private UclOpenAuditoryVrCorridorTaskParameters _taskParameters;
    
        public UclOpenAuditoryVrCorridorTaskLogic()
        {
            _version = "0.0.0-rc1";
            _name = "UclOpenAuditoryVrCorridor";
            _taskParameters = new UclOpenAuditoryVrCorridorTaskParameters();
        }
    
        protected UclOpenAuditoryVrCorridorTaskLogic(UclOpenAuditoryVrCorridorTaskLogic other)
        {
            _version = other._version;
            _name = other._name;
            _taskParameters = other._taskParameters;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Name of the task logic
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        [System.ComponentModel.DescriptionAttribute("Name of the task logic")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("taskParameters")]
        public UclOpenAuditoryVrCorridorTaskParameters TaskParameters
        {
            get
            {
                return _taskParameters;
            }
            set
            {
                _taskParameters = value;
            }
        }
    
        public System.IObservable<UclOpenAuditoryVrCorridorTaskLogic> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenAuditoryVrCorridorTaskLogic(this)));
        }
    
        public System.IObservable<UclOpenAuditoryVrCorridorTaskLogic> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenAuditoryVrCorridorTaskLogic(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("TaskParameters = " + _taskParameters);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Task parameters that map to Bonsai BehaviorSubject nodes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Task parameters that map to Bonsai BehaviorSubject nodes.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenAuditoryVrCorridorTaskParameters
    {
    
        private int _shapingStage;
    
        private int _startFreq;
    
        private int _endFreq;
    
        private ThresholdFrequencies _thresholdFrequencies;
    
        private PunishmentConfig _punishment;
    
        private double _amplitude;
    
        private int _quantizeBinSize;
    
        public UclOpenAuditoryVrCorridorTaskParameters()
        {
            _shapingStage = 1;
            _startFreq = 2000;
            _endFreq = 25000;
            _thresholdFrequencies = new ThresholdFrequencies();
            _punishment = new PunishmentConfig();
            _amplitude = 0.5D;
            _quantizeBinSize = 1;
        }
    
        protected UclOpenAuditoryVrCorridorTaskParameters(UclOpenAuditoryVrCorridorTaskParameters other)
        {
            _shapingStage = other._shapingStage;
            _startFreq = other._startFreq;
            _endFreq = other._endFreq;
            _thresholdFrequencies = other._thresholdFrequencies;
            _punishment = other._punishment;
            _amplitude = other._amplitude;
            _quantizeBinSize = other._quantizeBinSize;
        }
    
        /// <summary>
        /// Shaping stage (1-6)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("shapingStage")]
        [System.ComponentModel.DescriptionAttribute("Shaping stage (1-6)")]
        public int ShapingStage
        {
            get
            {
                return _shapingStage;
            }
            set
            {
                _shapingStage = value;
            }
        }
    
        /// <summary>
        /// Start frequency of the sweep (Hz)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("startFreq")]
        [System.ComponentModel.DescriptionAttribute("Start frequency of the sweep (Hz)")]
        public int StartFreq
        {
            get
            {
                return _startFreq;
            }
            set
            {
                _startFreq = value;
            }
        }
    
        /// <summary>
        /// End frequency of the sweep (Hz)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("endFreq")]
        [System.ComponentModel.DescriptionAttribute("End frequency of the sweep (Hz)")]
        public int EndFreq
        {
            get
            {
                return _endFreq;
            }
            set
            {
                _endFreq = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("thresholdFrequencies")]
        public ThresholdFrequencies ThresholdFrequencies
        {
            get
            {
                return _thresholdFrequencies;
            }
            set
            {
                _thresholdFrequencies = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("punishment")]
        public PunishmentConfig Punishment
        {
            get
            {
                return _punishment;
            }
            set
            {
                _punishment = value;
            }
        }
    
        /// <summary>
        /// Audio amplitude (0.0 to 1.0)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("amplitude")]
        [System.ComponentModel.DescriptionAttribute("Audio amplitude (0.0 to 1.0)")]
        public double Amplitude
        {
            get
            {
                return _amplitude;
            }
            set
            {
                _amplitude = value;
            }
        }
    
        /// <summary>
        /// Bin size for frequency quantization (Hz)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("quantizeBinSize")]
        [System.ComponentModel.DescriptionAttribute("Bin size for frequency quantization (Hz)")]
        public int QuantizeBinSize
        {
            get
            {
                return _quantizeBinSize;
            }
            set
            {
                _quantizeBinSize = value;
            }
        }
    
        public System.IObservable<UclOpenAuditoryVrCorridorTaskParameters> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenAuditoryVrCorridorTaskParameters(this)));
        }
    
        public System.IObservable<UclOpenAuditoryVrCorridorTaskParameters> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenAuditoryVrCorridorTaskParameters(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ShapingStage = " + _shapingStage + ", ");
            stringBuilder.Append("StartFreq = " + _startFreq + ", ");
            stringBuilder.Append("EndFreq = " + _endFreq + ", ");
            stringBuilder.Append("ThresholdFrequencies = " + _thresholdFrequencies + ", ");
            stringBuilder.Append("Punishment = " + _punishment + ", ");
            stringBuilder.Append("Amplitude = " + _amplitude + ", ");
            stringBuilder.Append("QuantizeBinSize = " + _quantizeBinSize);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<BehaviorBoard> source)
        {
            return Process<BehaviorBoard>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraController> source)
        {
            return Process<CameraController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PulseController> source)
        {
            return Process<PulseController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PulseWidths> source)
        {
            return Process<PulseWidths>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PunishmentConfig> source)
        {
            return Process<PunishmentConfig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RunningWheelModule> source)
        {
            return Process<RunningWheelModule>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Stage> source)
        {
            return Process<Stage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ThresholdFrequencies> source)
        {
            return Process<ThresholdFrequencies>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenAuditoryVrCorridorRig> source)
        {
            return Process<UclOpenAuditoryVrCorridorRig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenAuditoryVrCorridorTaskLogic> source)
        {
            return Process<UclOpenAuditoryVrCorridorTaskLogic>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenAuditoryVrCorridorTaskParameters> source)
        {
            return Process<UclOpenAuditoryVrCorridorTaskParameters>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BehaviorBoard>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PulseController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PulseWidths>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PunishmentConfig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RunningWheelModule>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Stage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ThresholdFrequencies>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenAuditoryVrCorridorRig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenAuditoryVrCorridorTaskLogic>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenAuditoryVrCorridorTaskParameters>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<BehaviorBoard>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}